# Generated by Django 5.0.3 on 2024-03-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_livro_capa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='name',
            new_name='nome',
        ),
    ]
